const express = require('express');
const controller = require('../controllers/dashboard.controller');
const auth = require('../middlewares/auth.middleware');
const allowRoles = require('../middlewares/rbac.middleware');
const router = express.Router();
router.use(auth);
router.get('/summary', allowRoles('ADMIN', 'HR_MANAGER'), controller.getSummary);
router.get('/leave-stats', allowRoles('ADMIN', 'HR_MANAGER', 'MANAGER'), controller.getLeaveStats);
router.get('/payroll-stats', allowRoles('ADMIN', 'HR_MANAGER', 'FINANCE'), controller.getPayrollStats);
router.get('/performance-stats', allowRoles('ADMIN', 'HR_MANAGER'), controller.getPerformanceStats);
module.exports = router;
