const express = require('express');
const authRoutes = require('./auth.routes');
const employeeRoutes = require('./employee.routes');
const departmentRoutes = require('./department.routes');
const positionRoutes = require('./position.routes');
const leaveRoutes = require('./leave.routes');
const payrollRoutes = require('./payroll.routes');
const performanceRoutes = require('./performance.routes');
const dashboardRoutes = require('./dashboard.routes');
const router = express.Router();
router.use('/auth', authRoutes);
router.use('/employees', employeeRoutes);
router.use('/departments', departmentRoutes);
router.use('/positions', positionRoutes);
router.use('/leaves', leaveRoutes);
router.use('/payroll', payrollRoutes);
router.use('/performance', performanceRoutes);
router.use('/dashboard', dashboardRoutes);
module.exports = router;
