const express = require('express');
const controller = require('../controllers/performance.controller');
const auth = require('../middlewares/auth.middleware');
const allowRoles = require('../middlewares/rbac.middleware');
const validate = require('../middlewares/validator.middleware');
const { createPeriodSchema, updatePeriodSchema, createGoalSchema, updateGoalSchema, selfScoreSchema, managerScoreSchema } = require('../validators/performance.validator');
const router = express.Router();
router.use(auth);
router.get('/periods', controller.listPeriods);
router.post('/periods', allowRoles('ADMIN', 'HR_MANAGER'), validate(createPeriodSchema), controller.createPeriod);
router.patch('/periods/:id', allowRoles('ADMIN', 'HR_MANAGER'), validate(updatePeriodSchema), controller.updatePeriod);
router.get('/goals', controller.listGoals);
router.post('/goals', allowRoles('ADMIN', 'HR_MANAGER', 'MANAGER'), validate(createGoalSchema), controller.createGoal);
router.put('/goals/:id', allowRoles('ADMIN', 'HR_MANAGER', 'MANAGER'), validate(updateGoalSchema), controller.updateGoal);
router.patch('/goals/:id/self-score', allowRoles('EMPLOYEE'), validate(selfScoreSchema), controller.selfScoreGoal);
router.patch('/goals/:id/manager-score', allowRoles('ADMIN', 'HR_MANAGER', 'MANAGER'), validate(managerScoreSchema), controller.managerScoreGoal);
router.get('/evaluations', controller.listEvaluations);
router.get('/reports', allowRoles('ADMIN', 'HR_MANAGER'), controller.getReports);
module.exports = router;
