const express = require('express');
const controller = require('../controllers/position.controller');
const auth = require('../middlewares/auth.middleware');
const allowRoles = require('../middlewares/rbac.middleware');
const router = express.Router();
router.use(auth);
router.get('/', controller.listPositions);
router.post('/', allowRoles('ADMIN', 'HR_MANAGER'), controller.createPosition);
router.put('/:id', allowRoles('ADMIN', 'HR_MANAGER'), controller.updatePosition);
module.exports = router;
