const express = require('express');
const controller = require('../controllers/announcement.controller');
const auth = require('../middlewares/auth.middleware');
const allowRoles = require('../middlewares/rbac.middleware');
const router = express.Router();
router.use(auth);
router.get('/active', controller.getActiveAnnouncements);
router.get('/', allowRoles('ADMIN', 'HR_MANAGER'), controller.listAnnouncements);
router.post('/', allowRoles('ADMIN', 'HR_MANAGER'), controller.createAnnouncement);
router.put('/:id', allowRoles('ADMIN', 'HR_MANAGER'), controller.updateAnnouncement);
router.delete('/:id', allowRoles('ADMIN', 'HR_MANAGER'), controller.deleteAnnouncement);
module.exports = router;