const express = require('express');
const controller = require('../controllers/auth.controller');
const auth = require('../middlewares/auth.middleware');
const validate = require('../middlewares/validator.middleware');
const { loginSchema, refreshSchema, logoutSchema, changePasswordSchema } = require('../validators/auth.validator');
const router = express.Router();
router.post('/login', validate(loginSchema), controller.login);
router.post('/refresh', validate(refreshSchema), controller.refresh);
router.post('/logout', validate(logoutSchema), controller.logout);
router.post('/change-password', auth, validate(changePasswordSchema), controller.changePassword);
module.exports = router;
