const express = require('express');
const controller = require('../controllers/employee.controller');
const auth = require('../middlewares/auth.middleware');
const allowRoles = require('../middlewares/rbac.middleware');
const validate = require('../middlewares/validator.middleware');
const { createEmployeeSchema, updateEmployeeSchema, updateStatusSchema } = require('../validators/employee.validator');
const router = express.Router();
router.use(auth);
router.get('/', allowRoles('ADMIN', 'HR_MANAGER', 'MANAGER'), controller.listEmployees);
router.get('/:id', allowRoles('ADMIN', 'HR_MANAGER', 'MANAGER', 'EMPLOYEE', 'FINANCE'), controller.getEmployeeById);
router.post('/', allowRoles('ADMIN', 'HR_MANAGER'), validate(createEmployeeSchema), controller.createEmployee);
router.put('/:id', allowRoles('ADMIN', 'HR_MANAGER'), validate(updateEmployeeSchema), controller.updateEmployee);
router.patch('/:id/status', allowRoles('ADMIN', 'HR_MANAGER'), validate(updateStatusSchema), controller.updateEmployeeStatus);
module.exports = router;
