const express = require('express');
const controller = require('../controllers/employee.controller');
const exportController = require('../controllers/employeeExport.controller');
const auth = require('../middlewares/auth.middleware');
const allowRoles = require('../middlewares/rbac.middleware');
const validate = require('../middlewares/validator.middleware');
const { createEmployeeSchema, updateEmployeeSchema, updateStatusSchema } = require('../validators/employee.validator');
const router = express.Router();
router.use(auth);
router.get('/org-chart', allowRoles('ADMIN', 'HR_MANAGER', 'MANAGER', 'EMPLOYEE'), require('../controllers/orgChart.controller').getOrgChart);
router.get('/export/excel', allowRoles('ADMIN', 'HR_MANAGER'), exportController.exportExcel);
router.get('/', allowRoles('ADMIN', 'HR_MANAGER', 'MANAGER'), controller.listEmployees);
router.get('/:id', allowRoles('ADMIN', 'HR_MANAGER', 'MANAGER', 'EMPLOYEE', 'FINANCE'), controller.getEmployeeById);
router.get('/:id/profile-summary', allowRoles('ADMIN', 'HR_MANAGER', 'MANAGER', 'EMPLOYEE'), controller.getProfileSummary);
router.get('/:id/leave-history', allowRoles('ADMIN', 'HR_MANAGER', 'MANAGER', 'EMPLOYEE'), controller.getLeaveHistory);
router.get('/:id/payroll-history', allowRoles('ADMIN', 'HR_MANAGER', 'FINANCE', 'EMPLOYEE'), controller.getPayrollHistory);
router.get('/:id/change-history', allowRoles('ADMIN', 'HR_MANAGER'), require('../controllers/history.controller').getChangeHistory);
router.get('/:id/documents', allowRoles('ADMIN', 'HR_MANAGER', 'EMPLOYEE'), require('../controllers/document.controller').listDocuments);
router.post('/:id/documents', allowRoles('ADMIN', 'HR_MANAGER'), require('../controllers/document.controller').uploadDocument);
router.get('/:id/documents/:docId', allowRoles('ADMIN', 'HR_MANAGER', 'EMPLOYEE'), require('../controllers/document.controller').downloadDocument);
router.delete('/:id/documents/:docId', allowRoles('ADMIN', 'HR_MANAGER'), require('../controllers/document.controller').deleteDocument);
router.get('/:id/performance-history', allowRoles('ADMIN', 'HR_MANAGER', 'MANAGER', 'EMPLOYEE'), controller.getPerformanceHistory);
router.post('/', allowRoles('ADMIN', 'HR_MANAGER'), validate(createEmployeeSchema), controller.createEmployee);
router.put('/:id', allowRoles('ADMIN', 'HR_MANAGER'), validate(updateEmployeeSchema), controller.updateEmployee);
router.patch('/:id/status', allowRoles('ADMIN', 'HR_MANAGER'), validate(updateStatusSchema), controller.updateEmployeeStatus);
module.exports = router;