const express = require('express');
const authRoutes = require('./auth.routes');
const employeeRoutes = require('./employee.routes');
const departmentRoutes = require('./department.routes');
const positionRoutes = require('./position.routes');
const leaveRoutes = require('./leave.routes');
const payrollRoutes = require('./payroll.routes');
const performanceRoutes = require('./performance.routes');
const dashboardRoutes = require('./dashboard.routes');
const auditRoutes = require('./audit.routes');
const announcementRoutes = require('./announcement.routes');
const parameterRoutes = require('./parameter.routes');
const notificationRoutes = require('./notification.routes');
const reportRoutes = require('./reports.routes');
const router = express.Router();
router.use('/auth', authRoutes);
router.use('/employees', employeeRoutes);
router.use('/departments', departmentRoutes);
router.use('/positions', positionRoutes);
router.use('/leaves', leaveRoutes);
router.use('/payroll', payrollRoutes);
router.use('/performance', performanceRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/announcements', announcementRoutes);
router.use('/parameters', parameterRoutes);
router.use('/notifications', notificationRoutes);
router.use('/reports', reportRoutes);
module.exports = router;