const express = require('express');
const controller = require('../controllers/leave.controller');
const auth = require('../middlewares/auth.middleware');
const allowRoles = require('../middlewares/rbac.middleware');
const validate = require('../middlewares/validator.middleware');
const { createLeaveSchema, rejectLeaveSchema } = require('../validators/leave.validator');
const router = express.Router();
router.use(auth);
router.get('/', allowRoles('ADMIN', 'HR_MANAGER', 'MANAGER', 'EMPLOYEE'), controller.listLeaves);
router.post('/', allowRoles('ADMIN', 'HR_MANAGER', 'MANAGER', 'FINANCE', 'EMPLOYEE'), validate(createLeaveSchema), controller.createLeave);
router.patch('/:id/approve', allowRoles('ADMIN', 'HR_MANAGER', 'MANAGER'), controller.approveLeave);
router.patch('/:id/reject', allowRoles('ADMIN', 'HR_MANAGER', 'MANAGER'), validate(rejectLeaveSchema), controller.rejectLeave);
router.patch('/:id/cancel', allowRoles('ADMIN', 'HR_MANAGER', 'EMPLOYEE'), controller.cancelLeave);
router.get('/leave-types/all', controller.listLeaveTypes);
router.post('/leave-types', allowRoles('ADMIN', 'HR_MANAGER'), controller.createLeaveType);
router.get('/balances/:employeeId?', allowRoles('ADMIN', 'HR_MANAGER', 'EMPLOYEE'), controller.getLeaveBalance);
router.get('/calendar/all', controller.getLeaveCalendar);
router.get('/employee-info/:employeeId', allowRoles('ADMIN', 'HR_MANAGER', 'MANAGER', 'EMPLOYEE'), controller.getEmployeeLeaveInfo);
module.exports = router;
