const express = require('express');
const controller = require('../controllers/notification.controller');
const auth = require('../middlewares/auth.middleware');
const router = express.Router();
router.use(auth);
router.get('/', controller.getNotifications);
router.get('/unread-count', controller.getUnreadCount);
router.patch('/:id/read', controller.markAsRead);
router.patch('/read-all', controller.markAllAsRead);
module.exports = router;