const express = require('express');
const controller = require('../controllers/payroll.controller');
const exportCtrl = require('../controllers/payrollExport.controller');
const auth = require('../middlewares/auth.middleware');
const allowRoles = require('../middlewares/rbac.middleware');
const validate = require('../middlewares/validator.middleware');
const { runPayrollSchema, calculatePayrollSchema, generatePayrollSchema } = require('../validators/payroll.validator');
const router = express.Router();
router.use(auth);
router.post('/calculate', allowRoles('ADMIN', 'HR_MANAGER', 'FINANCE'), validate(calculatePayrollSchema), controller.calculate);
router.post('/generate', allowRoles('ADMIN', 'HR_MANAGER'), validate(generatePayrollSchema), controller.generate);
router.post('/run', allowRoles('ADMIN', 'HR_MANAGER'), validate(runPayrollSchema), controller.runPayroll);
router.get('/my', allowRoles('EMPLOYEE'), controller.getMyPayrolls);
router.get('/export/single/:id', allowRoles('ADMIN', 'HR_MANAGER', 'FINANCE'), exportCtrl.exportSinglePayroll);
router.get('/export/bulk', allowRoles('ADMIN', 'HR_MANAGER', 'FINANCE'), exportCtrl.exportBulkPayroll);
router.get('/reports/cost', allowRoles('ADMIN', 'HR_MANAGER', 'FINANCE'), controller.getCostReport);
router.get('/parameters', allowRoles('ADMIN', 'HR_MANAGER', 'FINANCE'), controller.listParameters);
router.get('/period/:year/:month', allowRoles('ADMIN', 'HR_MANAGER', 'FINANCE'), controller.getPayrollsByPeriod);
router.get('/employee/:employeeId', allowRoles('ADMIN', 'HR_MANAGER', 'FINANCE', 'EMPLOYEE'), controller.getPayrollsByEmployee);
router.get('/', allowRoles('ADMIN', 'HR_MANAGER', 'FINANCE'), controller.listPayrolls);
router.get('/:id', allowRoles('ADMIN', 'HR_MANAGER', 'FINANCE', 'EMPLOYEE'), controller.getPayrollById);
router.put('/:id/approve', allowRoles('ADMIN', 'HR_MANAGER', 'FINANCE'), controller.approvePayroll);
router.put('/:id/cancel', allowRoles('ADMIN', 'HR_MANAGER'), controller.cancelPayroll);
module.exports = router;